### ISSUE TITLE
Cant connect: Invalid session

### ISSUE THREAD

**Issue by HardSer** [minecraftly/minecraftly#17]
Hi!
Cant connect to m.ly/minecraftly.com. It show the error:
![2016-08-02_11 29 06](https://cloud.githubusercontent.com/assets/9827543/17359815/f9e778bc-5970-11e6-91d0-8a181cabe8f6.png). [Invalid session(try restarting)]

Using Optifine 1.8. Cracked.

**Comment by SilverCory** [comment]
Hey there, this is caused because this isn't a cracked server. Sorry.
