### ISSUE TITLE
Grief bug

### ISSUE THREAD

**Issue by viet** [minecraftly/minecraftly#30]
A player reported it to me and I tested. I was able to grief any player's world.

Reproduction:
1. I trust myself in my own world
2. Wait til server auto reboot
3. Do /world <name> and grief anyone's world as I like.

**Comment by SilverCory** [comment]
It only works if you trust yourself and not if you're trusted in another world?

**Comment by viet** [comment]
Yeah, that's right.

**Comment by SilverCory** [comment]
@viet Has this been fixed?

**Comment by viet** [comment]
No, not yet.
