### ISSUE TITLE
EChest or something alike.

### ISSUE THREAD

**Issue by SilverCory** [minecraftly/minecraftly#36]
Global inventories?

**Comment by viet** [comment]
Currently we are using the external plugin ChestMaster: https://www.spigotmc.org/resources/chestmaster.3157/

If there's a way to extend the current inventory without typing /chest, the interface would make worth it to try.

**Comment by SilverCory** [comment]
@viet is that plugn global?

**Comment by viet** [comment]
Yeah it's global.

It's database is MySQL

**Comment by SilverCory** [comment]
Ahh sexy, no dire need then :P
