### ISSUE TITLE
Feature Request: Command /world {username}

### ISSUE THREAD

**Issue by viet** [minecraftly/minecraftly#9]
This command will:

- Teleport yourself to another player's server for easy navigation around the network
- If the server is whitelisted, then don't teleport yourself.

Command format: /world {username}

Example: /world notch

**Comment by SilverCory** [comment]
Can we close this along with
0f1c34337856e96145d7a983d64e4c2a6d955084
42a94c92146084fd1ae892ad52b085bdbe896c4a

**Comment by viet** [comment]
Yeah!
